### ISSUE TITLE
store.off() can cause listeners to be out of order

### ISSUE THREAD

**Issue by btakita** [nanostores/nanostores#101]
I have a large graph of `computed` along w/ some slow async requests which set the value of the upstream `deps` atoms. The listeners on the `deps` are in the correct order. Then `store.off()` is triggered for some of the listeners, after `STORE_UNMOUNT_DELAY = 1000` ms. Then the removed listeners are readded. Afterwards, the listeners on the `deps` are in the incorrect order.

If I manually increase `STORE_UNMOUNT_DELAY = 100000`, then the issue does not occur since `store.off()` is not called.

**Comment by btakita** [comment]
Another factor is a leaf `computed` is subscribed to by a UI component, yet the leaf `computed` dependency `computed` is not subscribed to. This causes the leaf `computed` to not have `store.off()` called & the dependency `computed` to have `store.off()` called. When the dependency `computed` is readded, the listener is appended after the leaf `computed` listener.

**Comment by btakita** [comment]
Possibly related to https://github.com/nanostores/nanostores/issues/100

**Comment by ai** [comment]
Yes, very likely it is relevant.

Sorry, I am not in good condition for complex event problems because of the war. I will try to look on this week, but can’t guarantee (PR will be the better option).

**Comment by btakita** [comment]
I actually fixed a similar bug w/ svelte stores using breadth-first instead of depth-first resolution.

https://github.com/sveltejs/svelte/pull/3219

Take care
