### ISSUE TITLE
404 when importing useStore from https://unpkg.com/@nanostores/preact?module

### ISSUE THREAD

**Issue by d-v** [nanostores/nanostores#104]
Have a basic Preact app running in electron and cannot import `useStore`. The import statement `import { useStore } from 'https://unpkg.com/@nanostores/preact?module'` gives 404.

![image](https://user-images.githubusercontent.com/7275135/158033123-8995780d-6b24-4471-9d03-4dc9615e1765.png)

Inspecting the output of https://unpkg.com/@nanostores/preact?module I see `import { useState, useEffect } from  "https://unpkg.com/preact@>=10.0.0/hooks?module"; `
https://unpkg.com/preact@>=10.0.0/hooks?module seems to be the url of the 404.
Navigating there in a web browser gives `Cannot find an index in "/hooks" in preact@10.6.6`

**Comment by ai** [comment]
I am not `unpkg` users. Can you send PR with correct import since you have better experience with `unpkg`?

**Comment by d-v** [comment]
Thank you for the hint, I used vite instead and was able to get it working with storeon.
