### ISSUE TITLE
How to do async fetch in MapTemplate?

### ISSUE THREAD

**Issue by tavoli** [nanostores/nanostores#108]
I want to do an async fetch in mapTemplate If not find data in memory/cache. But, I try using task or promise, and yet startTask with end using await allTasks, but how I say, not is possible to do this in mapTemplate?

I tried:
```
export const Product = mapTemplate<ProductType>((newProduct, id) => {
  let product: ProductType

  if (products.get().length) {
    product = products.get().find(product => product.id === id)
  }

  if (product) {
    newProduct.set(product)
  } else {
    const end = startTask();

    (async () => {
      await task(async () => {
        const { data } = await graphql(getProductByIdQuery(id))
        newProduct.set(transform(data.products.data))
        end()
      })
    })();
  }
});
```
and in my test (I`m using uvu):
```
it("should get one product by graphql", async () => {
  stubFetch.returns(
    Promise.resolve({
      json: () => ({ ...oneProductGraphql })
    })
  )
  const product = Product(oneProduct.id)
  await allTasks()
  console.log(product.get())
})
```
and test print: 

`{ id: '1' }`

I am sure that my code is wrong, but I don't know what it is. Can please help me?

**Comment by ai** [comment]
`mapTemplate` store is a lazy store.

Constructor will be called only when somebody will subscribe to the store.

Add `keepMount(product)` to the test (before `allTasks`).

**Comment by tavoli** [comment]
I understand. it works!. I think that wait `allTasks` can have `keepMount` internally. Because think with me: When I can want to wait for allTasks from `mapTemplate` without waiting for async executions?

**Comment by ai** [comment]
Test could relay of special order of store mounting. We need to mount store explicitly in tests.

I added another note to docs 41471e5
