### ISSUE TITLE
Support for SolidJS

### ISSUE THREAD

**Issue by nikitavoloboev** [nanostores/nanostores#111]
I am not sure how much it would make sense to port nanostores to [SolidJS](https://www.solidjs.com) as it uses a very different way to render things without VDOM than React. But since nanostores already supports Svelte as it says in description, it would be awesome to have support for SolidJS added to.

**Comment by ai** [comment]
Seems like we already have a compatibility layer https://github.com/nanostores/solid

**Comment by ai** [comment]
I also added Solid to main docs to fix problem with discoverability

https://github.com/nanostores/nanostores#solid=
