### ISSUE TITLE
maptemplate crud example

### ISSUE THREAD

**Issue by mapsgeek** [nanostores/nanostores#118]
I'm trying to make a crud operation but following the docs it seems like using maptemplate is the way over using an array
but i don't understand how to iterate over the maptemplate or delete items from the map.

can you please provide a todo list crud example?

**Comment by ai** [comment]
Here is an example of using map templates for CRUD from Logux https://github.com/logux/client/blob/main/sync-map-template/index.js

1. It has `useFilter()` which return another store with a list of items (to iterate over)
2. There is `deleteMapSync(id)` function (store with list, listen for these calls).

If it looks like too complicated for your case, you can create an `atom()` with a list. You are not locked on map template (honestly, map template was created for very advanced CRUD systems of top of operations log and CRDT).
