### ISSUE TITLE
 "node": "^14.0.0 || ^16.0.0 || >=18.0.0" is anything wrong with version 17

### ISSUE THREAD

**Issue by shiftlabs1** [nanostores/nanostores#124]
I am getting the error below when building on cloudflare 
```
error nanostores@0.7.0: The engine "node" is incompatible with this module. Expected version "^14.0.0 || ^16.0.0 || >=18.0.0". Got "17.9.0"
```
Is there an issue with node version 17 (the highest version supported by cloudflare). setting , 14, 16 and versions equal to or above 18 is restrictive. how about setting to 
```
>=14.0.0
```

**Comment by ai** [comment]
Node.js 17 is not supported anymore https://github.com/nodejs/release#release-schedule

Don’t use odd versions of Node.js. It is preview versions for developers, not stable versions for production.
