### ISSUE TITLE
Using the callback value rather than the original store value in an action

### ISSUE THREAD

**Issue by ajhaupt7** [nanostores/nanostores#128]
Hello, I've been using nanostores in React and it's worked great so far! I just had a clarifying question about working with actions. In doing something like this:

```
export const onSetLocation = action(originalStoreValue, 'setLocation', (callbackStoreValue, value: Location) => {
  callbackStoreValue.setKey('location', value);
});
```

Is there a danger (or reason not to do it) in using the store value that was passed to the action originally rather than the store value that is passed to the callback? If they refer to the same object, why pass it to the callback? Naming becomes a bit confusing here -- I've been prefacing the callback values with an underscore and using that within the callback, but have not seen a difference in behavior when trying to use the original value itself. Thanks again!

**Comment by ai** [comment]
> Is there a danger (or reason not to do it) in using the store value that was passed to the action originally rather than the store value that is passed to the callback?

No, `value `argument is just a syntax sugar.

`get()` call is a little more expensive than using `value` but it is a microoptimization.
