### ISSUE TITLE
Wrong numbers for computed

### ISSUE THREAD

**Issue by artalar** [nanostores/nanostores#134]
Hi! Im [trying to add](https://github.com/artalar/reactive-computed-bench/blob/main/computers_bench.ts#L241) nanostores to [my bench](https://github.com/artalar/reactive-computed-bench) and get this error

> Expected "18", received "26"

<img width="251" alt="image" src="https://user-images.githubusercontent.com/27290320/203780604-b2fe7c38-ee82-4344-bdb2-2302d2478fdb.png">

Looks like there is glitch somewhere, or I have a mistake in atoms definitions?

**Comment by kimoofey** [comment]
Hi @artalar 
Seems like on line 250 of your bench `const a = computed(entry, (entry) => entry + 1)`

should be `const a = computed(entry, (entry) => entry)`

I see on other test cases a value without any incrementations.
Correct me if I'm wrong

**Comment by artalar** [comment]
@kimoofey you are right! Without this mistake nanostores score is at the top of the list! Will publish update in a couple of days
