### ISSUE TITLE
Seems like diamond dependency problem is still unsolved

### ISSUE THREAD

**Issue by istarkov** [nanostores/nanostores#135]
[Here](https://github.com/nanostores/nanostores/pull/58/files) block 
```
### Diamond Problem
To make stores simple and small, Nano Stores doesn’t solve “Diamond problem”.
```
was removed from the readme. 

But simple test
```ts
import { atom, computed } from 'nanostores';
const main = atom(0);
const comp_a = computed(main, (v) => v);
const comp_b = computed(comp_a, (v) => v);
const last = computed([comp_a, comp_b], (a, b) => `${a} ${b}`);
last.subscribe((v) => {
  console.log('LAST', v);
});
main.set(1);
```

gives output

```log
LAST 0 0
LAST 1 0
LAST 1 1
```
So seems like the problem still exists or probably I don't understand the problem well and it's something other.
It doesn't somehow affect me, just found that [diamond](https://github.com/nanostores/nanostores/blob/main/computed/index.js#L7-L20) code playing with sources of this beautiful library, and haven't got how it could solve something like the above.

**Comment by ai** [comment]
Could be related with https://github.com/nanostores/nanostores/issues/134

I am thinking of going into it later.

**Comment by codeninja-ru** [comment]
so I submitted a PR for this #144 

the test case is

```javascript
test('prevents extra calls in a diamond', () => {
  const main = atom(0)
  const comp_a = computed(main, (v) => v)
  const comp_b = computed(comp_a, (v) => v)
  const last = computed([comp_a, comp_b], (a, b) => `${a} ${b}`)
  const events = []
  last.subscribe((v) => {
    events.push('LAST ' + v);
  });
  main.set(1)
  clock.runAll()

  equal(events, [
    'LAST 0 0',
    'LAST 1 1',
  ])

})

```

**Comment by Stas-tolpekin** [comment]
Looks like to achieve the goal, it’s necessary to have an event channel to pass a message from parent store to children. Having this, the algorithm of setting the state can be the following:

1. The store sets the new value and passes the value to all children. (Children perform their logic upon of a parent state change, but do not call `listen` and `subscribe` callbacks)
2. The store send an event to all children to signal that all stores in the chain handled the new value. (On getting the event children call `listen` and `subscribe` callbacks)

This algorithm can be performed synchronously (without setTimeout). There could be applied additional optimizations (for instance, postpone calculation of value before getting the event if there are no any children). But looks like this approach can turn this simple store to pretty heavy construction.

**Comment by ramil-k** [comment]
I created a draft PR with my idea to solve this problem https://github.com/nanostores/nanostores/pull/146

**Comment by ai** [comment]
Should be fixed https://github.com/nanostores/nanostores/pull/145
