### ISSUE TITLE
Add a note about React not triggering a render for `store.notify()` for non primitive values.

### ISSUE THREAD

**Issue by AleVul** [nanostores/nanostores#137]
The example provided in readme won't trigger a react render when mutating a non primitive value.
```
store.get().bigList.push(newItem)
store.notify('bigList')
```

[useSyncExternalStore](https://beta.reactjs.org/reference/react/useSyncExternalStore#parameters)'s docs explain that React internally uses `Object.is` to detected whether the value changed or not. If the reference to the value remains the same, but the store notifies that something changed, react will choose to ignore that notification.

In this case, React users that want a render to trigger have to change the reference.

**Comment by ai** [comment]
Yes, good idea. I removed it 456c2c1

Anyway it is too dirty hack (but we will keep it for Svelte users for instance)
