### ISSUE TITLE
How to work with nested objects?

### ISSUE THREAD

**Issue by anton-at-bay** [nanostores/nanostores#141]
Hello all,

Thanks for the nanostores, my goto tool to handle state in all types of projects 🙏 

I haven't found a way to handle nested objects update when using the map. 

```
const state = map({
  1: { address: { street: 'Hello' }},
  2: { address: { street: 'Hello 2' }},
})
```

How do I update street for the second item? 

Many thanks in advance!

**Comment by ai** [comment]
There is no special API and we do not plan to add API to the core to keep core minimalistic.

Here are options:

1. Use JS destructors:

```js
state.setKey(2, { ...state.get()[2], street: 'New' })
```

2. Add an action function and hide nested object changes inside:

```js
export function changeState(id, key, value) {
  state.setKey(id, { ...state.get()[id], [key]: value })
}
```

```js
import { changeState, state } from '../stores/state'

changeState(id, 'street', 'New')
```

**Comment by euaaaio** [comment]
@ai, let’s convert this into discussion, since we have them
