### ISSUE TITLE
Feature Request - Multiple stores listener.

### ISSUE THREAD

**Issue by angelcervera** [nanostores/nanostores#158]
Like with `computed`, would be possible to have a `listen` function to be able to listen more than one storage at the same time?

Something like this:
```ts
listen([profile, users], (values, changes) => {
  console.log(`${changes} new value ${value[values]}`)
})
```

**Comment by ai** [comment]
The helpers will be very simple:

```js
function listenMany (stores, cb) {
  function listener () {
    cb(...stores.map(i => i.get()))
  }
  let unbinds = stores.map(i => i.listen(listener))
  return () => {
    unbinds.forEach(i => {
      i()
    })
  }
}
```

I don’t want to add it to the core, since users should use more `computed` (because it is simpler to debug and use in UI frameworks).

**Comment by angelcervera** [comment]
Hi @ai 
So maybe I'm doing something wrong. I need to do an async request when a store changes. Ex. `filter` store contains a set of filters to apply and I need to execute an **async** firestore call to retrieve new data. In my current implementation, I'm updating another storage call `items` with the response.

Important, it's a that the request is `async`.

I understand that the `computed` is not supporting async functions, right? So how to do it with computed?

**Comment by ai** [comment]
You need to use `computed` for `async` operations:

```js
let result = computed(filterStores, (...filterValues) => {
  result.set({ isLoading: true })
  getData(filterValues).then(data => {
    result.set({ isLoading: false, data })
  })
})
```

Don’t forget that async callback can be called in a different order. You need to check that you received response of the latest request:

```diff
+ let lastRequest = 0

  let result = computed(filterStores, (...filterValues) => {
+   let thisRequests = ++lastRequest
    result.set({ isLoading: true })
    getData(filterValues).then(data => {
+     if (thisRequests === lastRequest)
        result.set({ isLoading: false, data })
+     }
    })
  })
```
