### ISSUE TITLE
Passed in Map store for `actionFor` missing cache key

### ISSUE THREAD

**Issue by motleydev** [nanostores/nanostores#164]
TS is throwing an error that the ActionFor store input param is looking for a MapTemplate that requires a cache key. 

**Reference code:**

```js
import { map, actionFor } from "nanostores";
import { SEARCHING } from "./consts";

interface Search {
  results?: Record<string, string>[];
  searches?: string[];
  searching: SEARCHING;
}

export const searchStore = map<Search>({
  results: [],
  searches: [],
  searching: SEARCHING.NOT_SEARCHING,
});

export const search = actionFor(searchStore, "search", async (store, term) => {
  store.setKey("searching", SEARCHING.SEARCHING);
  try {
    const res = await fetch("/api/search", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        search: term,
      }),
    });
    const data = await res.json();
    store.setKey("results", data.results.results);
    store.setKey("searches", [
      ...store.get().searches,
      ...data.results.results,
    ]);
    store.setKey("searching", SEARCHING.NOT_SEARCHING);
  } catch (e) {}
});
```

**Error Message:**

```bash
Argument of type 'MapStore<Search>' is not assignable to parameter of type 'MapTemplate<any, any[], {}>'.
Property 'cache' is missing in type 'MapStore<Search>' but required in type 'MapTemplate<any, any[], {}>'.
```

**Comment by motleydev** [comment]
Wanted to bump this again to see if there's any additional info I can provide to be helpful. Thanks!

**Comment by ai** [comment]
Sorry, have too many open source project. Right now I stack on https://github.com/evilmartians/oklch-picker

**Comment by motleydev** [comment]
I wonder if I ha a misconception here.

Reading the docs I thought actionFor was for maps, but now reading again, I wonder if it's meant that actionFor is only for Map Templates? Is that correct?

I was digging into the code to make a PR, and that's where I discovered my possible misconception here.

**Comment by ai** [comment]
Yes, you should use just `action()` for stores and `actionFor()` for Map Template.

**Comment by motleydev** [comment]
I think the confusion for me was the difference between Maps and Atoms. 

So Maps and Atoms are (stores) and Map Templates provide the key level cache/id interface to know which Map to edit, is that about right?

**Comment by ai** [comment]
> Map Templates provide the key level cache/id interface to know which Map to edit, is that about right?

Map Template is a template to create maps stores with the same listeners and cache. Map Template is like a clase in object oriented programming.
