### ISSUE TITLE
Suggestion: MapStore removeKey method

### ISSUE THREAD

**Issue by raphaellaude** [nanostores/nanostores#165]
Would be great to be able to remove store values in MapStore using the key rather than having to update via the slightly more verbose:
```
delete store.get()[key];
store.notify();
```

**Comment by ai** [comment]
`Map#setKey(key, undefined)` removes key. 

https://github.com/nanostores/nanostores/blob/main/map/index.js#L7-L13

Should we improve docs or add extra method (with a price of increasing size)? What do you think?

**Comment by raphaellaude** [comment]
Ah, got it ~ that is doing the trick, Thank you. I came across that in the docs so should be fine, but avoided it because I forgot to allow the value to be undefined in ts.

**Comment by ai** [comment]
I imported docs e78c63c
