### ISSUE TITLE
Releases on github

### ISSUE THREAD

**Issue by dartess** [nanostores/nanostores#197]
Is it possible to use github's `releases`? Most of the packages I know have a "Releases" page with changelogs. This allows you to subscribe to new releases using the native Watch mechanism.

**Comment by dartess** [comment]
Unfortunately no.

> You can watch for tags :)

I don't seem to be able to get notifications for new tags.

I meant that you can subscribe to releases and receive notifications.

<img width="336" alt="image" src="https://github.com/nanostores/nanostores/assets/15047511/b78bd51f-b112-4c5c-9cef-9ee4b33aaaa1">

**Comment by dartess** [comment]
It seems releases are made from tags, and you are already actively using tags.
It would be great to publish releases, and instead of changelogs, put a link to the `CHANGELOG.md` file.

**Comment by dartess** [comment]
I don't have relevant experience.

**Comment by euaaaio** [comment]
We don’t need to invent the new one — https://github.com/yyx990803/release-tag

**Comment by azat-io** [comment]
+1 for releases. I use [GitHub release notify telegram bot](https://github.com/pyatyispyatil/github-releases-notify-bot) to get notification of new releases. This thing works just for GitHub releases.

[Release tag](https://github.com/yyx990803/release-tag) is the easiest way. But all the release messages will look something like [this](https://github.com/vuejs/vitepress/releases).

Personally, I prefer other tools, but they all work with [conventional commits](https://conventionalcommits.org/).

**Comment by ai** [comment]
Done https://github.com/nanostores/nanostores/blob/next/.github/workflows/release.yml
