### ISSUE TITLE
Advice for How to Use this Library with Jest

### ISSUE THREAD

**Issue by Bwvolleyball** [nanostores/nanostores#210]
I'm getting the following error:

```
    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /Users/user/Code/ui/node_modules/nanostores/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){export { action, lastAction } from './action/index.js'
                                                                                             ^^^^^^

    SyntaxError: Unexpected token 'export'

    > 1 | import { atom, WritableAtom } from 'nanostores';
```

I've explored all of the options in the `Here's what you can do` section of that error message to no avail, and I'm not really sure what to do next.

Is this something you've seen before with nanostores? How do I get past this? It works fine in the running app, just not the tests.

Additional context, this is an older react app (v16), using create-react-app and craco, so, I'm not sure if the jest advice isn't accurate, or if I'm not configuring it correctly for these tools. Any and all input is greatly appreciated.

**Comment by ai** [comment]
Nano Stores is ESM-only project. You must have ESM project (with `import` instead of `require()`) to use it.

Note, that if you are using TypeScript, you should be sure that compiled JS also have `import`.

**Comment by Bwvolleyball** [comment]
Yeah, our project is TypeScript. It works in the browser beautifully, I just haven't figured out why Jest is not happy with it.

**Comment by ai** [comment]
Google for `TypeScript ESM output` and `jest esm` (for your version). You need to have `type: "module"` in `package.json`.

**Comment by Bwvolleyball** [comment]
This was a complex problem, with a lot of nuance, so I'm going to post the pieces that worked for us for posterity sake.

Jest config block in `package.json`:

```json
  "jest": {
    "transformIgnorePatterns": [
      "!node_modules/" # This is overly aggressive, but mostly wanted to make sure jest was coping with any dependencies.
    ],
}
```

We clobbered all of node_modules because we long-term want to get off jest, so this was an easy way to just ensure jest can look at everything in the interim.

We are still on babel 6, so there is a newer version of this plugin if you find yourself on babel 7.
Babel configs (for us this is located in `craco.config.js`)

```javascript
  babel: {
    env: {
      test: {
        plugins: ['transform-es2015-modules-commonjs'] // let's babel tranform ESM modules to common js for the jest tests only.
      }
    }
  },
```

Lastly, Jest doesn't like the new style of `.umd.cjs` for some reason. The one project that has this that we noticed so far was `@nanostores/query`, so we had to shim together the right import for jest in a global mock:

`./src/setupTests.js`:
```javascript
// @nanostores/query has a `nanoquery.umd.cjs` and `nanoquery.js` file in it's distribution. Jest likes to latch onto `.umd.cjs`
// but this causes it to barf. Instead, we need it to latch onto the vanilla `.js` file.
// this is really only needed because Jest can't handle ESM modules, so, in combination with our converter, this helps it pick code it can read.
jest.mock('@nanostores/query', () => require('@nanostores/query/dist/nanoquery.js'));
```

If you use storybook on top of this, there is similar code required to make storybook happy with ESM modules (Storybook 6, that is, we are blocked from upgrading to Storybook 7 at the moment, where this might just work.)

`./.storybook/main.js`:
```javascript

```
module.exports = {
  webpackFinal: async (config, { configType }) => {
    webpackConfig.module.rules.push({
      test: /\.(?:js|ts|mjs|cjs)$/,
      include: /node_modules\/@?nanostores/,
      use: {
        loader: 'babel-loader',
        options: {
          plugins: [
            'transform-es2015-modules-commonjs' // babel 6 only, different for babel 7
          ],
        },
      },
    });

    // needed for compatability because this is a .umd.cjs file.
    webpackConfig.module.noParse = /@nanostores\/query/
  },
};
