### ISSUE TITLE
Untyped methods and arguments

### ISSUE THREAD

**Issue by gismya** [nanostores/nanostores#248]
Hello!

I'm implementing nanostores in a project and noticed that a few methods in the ReadableAtom are not reflected in the types. Specifically `notify`, and the arguments for `level` in the initializing function, and the arguments for `listenerLevel` in the `subscribe` and `listen` methods. Are they supposed to be internal or should they be included in the types? If so I can create a PR for that.

**Comment by ai** [comment]
We didn't add them to types, because they are semi-private methods.

For instance, `notify` requires a very good understanding of Nano Stores and UI framework rendering to be used correctly.

`level` prop is a tool for solving diamond dependencies problem.

So we don't need PR here.

**Comment by ai** [comment]
But why arguments in listeners are not types? They should.

**Comment by gismya** [comment]
I figured that could be the case for Notify and Level, but I had an actual use case for the `listenerLevel`. Should I submit a PR for that?

**Comment by gismya** [comment]
Figured it was easier if I submitted a PR while I still had it in mind, in case it was wanted.
