### ISSUE TITLE
Stronger type checking for action callback

### ISSUE THREAD

**Issue by gismya** [nanostores/nanostores#261]
The action callback is currently typed as 
``` 
function action<
  SomeStore extends WritableStore,
  Callback extends ($store: SomeStore, ...args: any[]) => any
>(store: SomeStore, actionName: string, cb: Callback): OmitFirstArg<Callback>
```

The callback arguments defaulting to `any` breaks strict type checking. Does it make sense for this package to change the typings to default to `unknown` instead? If so, I can look into it and create a PR.

**Comment by gismya** [comment]
My draft idea for it is to then type it something like 

```
export function action<
  SomeStore extends WritableStore,
  Args extends unknown[] = unknown[], 
  ReturnType = void
>(
  store: SomeStore,
  actionName: string,
  cb: (store: SomeStore, ...args: Args) => ReturnType
): (...args: Args) => ReturnType
```
but I haven't taken the time to investigate the deeper implications of that yet.

**Comment by ai** [comment]
We are planning to remove actions from next major release since the benefits compare to simple functions are not so great (only better logging and some sugar).

**Comment by gismya** [comment]
Then I'll abort converting the code base to using them and go back to simple functions. Thank you!
