### ISSUE TITLE
setKey with sub keys starting with numbers creates superfluous arrays

### ISSUE THREAD

**Issue by rderimay** [nanostores/nanostores#284]
This problem can easily be worked around but still it a pretty annoying one.

Say you have a `map` or `deepMap` and want to set a value for a sub key that starts with a number, then you will end up having a map containing an array of x items being set to `undefined`. The number of items equals the number the sub key starts with.

Example:

`myMap.setKey('debug.123456-whatever', 'TEST')` results in 
```
{
    debug: [
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        ... // 123456 items in total
         123456-whatever: 'TEST'
    ],
}
```

`myMap.setKey('debug.A123456-whatever', 'TEST')` would make no problem and result in 

```
{
    debug: {
        A123456-whatever: 'TEST'
    },
}
```

**Comment by ai** [comment]
cc @dkzlv

**Comment by ai** [comment]
Fixed in https://github.com/nanostores/nanostores/pull/289

We will release it during the week.
