### ISSUE TITLE
Deprecation warning on installation for a couple dependencies

### ISSUE THREAD

**Issue by AbdullahMuhammad** [nanostores/nanostores#287]
```
pnpm add nanostores
 WARN  2 deprecated subdependencies found: rollup-plugin-inject@3.0.2, sourcemap-codec@1.4.8
```

When do you plan to get rid of these dependencies and replace them with newer maintained versions or alternatives?

**Comment by ai** [comment]
`nanostores` has 0 dependencies https://www.npmjs.com/package/nanostores?activeTab=dependencies

This warning is because of other dependencies in your project (pnpm shows warning from all dependencies when you install something new).

BTW, respect for using `pnpm`. The best package manager ever.
