### ISSUE TITLE
Glitches (Diamond problem)

### ISSUE THREAD

**Issue by AlexandrHoroshih** [nanostores/nanostores#30]
Hi!
I was wondering, how `nanostores` handles cases with tricky dependencies, so i wrote a few tests to see, if `nanostores` is glitch-prone

`Effector` & `Reatom` tests were used as a reference:
* [`Reatom` tests](https://github.com/artalar/reatom/blob/next/packages/core/tests/diamond.test.ts)
* [`Effector` tests](https://github.com/effector/effector/blob/master/src/effector/__tests__/store/diamond-deps.test.ts)

1.  `Nanostores` tests for glitches and diamond problem - https://codesandbox.io/s/nanostores-glitches-2w42k?file=/src/nanostores.test.js
2. Comparison with `Rx`, `MobX` & `Effector`:
https://codesandbox.io/s/effector-comparison-forked-0bri6?file=/src/index.test.js (based on this [sandbox](https://codesandbox.io/s/effector-comparison-r9qy2))

And i found a few issues:

1. Only `Rx` & `Nanostores` are recalculating whole chain over and over again - for each update there is 3 triggers of "displayName" store subscribers - which is, obviously, bad for library performance, especially if stores combinations are getting more complicated

2. `nanostores` triggers subscribers at the end of the chain with intermediate, inconsistent values.
It happens, because `nanostores` doesn't wait for calculations in other branch to finish and proceeds to update store

As a result - store value becomes not convergent until second branch calculations are done - and store subscribers are triggered with invalid value too, so this inconvergence will be spreading further

It, probably, will not be a big problem for `React` - since `nanostores/react` uses `React`'s `batchedUpdates` function internally, so if inconvergent value is followed by convergent one - `React` will take only last and the correct one
But it will be the problem for all other subscribers without such batching mechanism - including other nanostores

**Expected behavior:**
I think that detecting if Store value is convergent (and that calculations cycle is over) should not be the problem of store consumers - and library must handle these cases internally (like `MobX`, `Effector` and `Reatom` do)

**Comment by ai** [comment]
I do not have a solution for this problem yet, but it will be better to cover this case.

It is not a high priority task for now, since the main use case of Nano Stores (in contrast with RX) is to have big stores, not small atomic reactive steps.

Ideas to solve the problem are welcome.

**Comment by AlexandrHoroshih** [comment]
I don't see how big stores would help with glitches 😕

User is allowed to combine nanostores regardless of their size - so diamond problem **will come** very soon anyway.
And it doesn't matter if it due to explicit (via few createDerived's) or implicit connection (like React component that listens to StoreOne and calls update to StoreTwo from useEffect)

> Ideas to solve the problem are welcome

I'm not a big specialist in building state-managers, but it seems that all (known to me) **glitch-less** state-managers have some sort of internal mechanism to schedule computations ([effector](https://github.com/effector/effector/blob/master/src/effector/kernel.ts), [Reatom's store](https://github.com/artalar/reatom/blob/next/packages/core/src/createStore.ts), [MobX](https://github.com/mobxjs/mobx/blob/main/packages/mobx/src/core/observable.ts)) - i don't see an easy way to implement such mechanism into `nanostores`, but it, probably, still needs one

**Comment by AlexandrHoroshih** [comment]
Also i updated [first sandbox](https://codesandbox.io/s/nanostores-glitches-2w42k?file=/src/nanostores.test.js) with a few tests on how `nanostores` behave, if store subscribers list is beign mutated during computations of these subscribers.
I borrowed these tests from Redux codebase (from [here and below](https://github.com/reduxjs/redux/blob/184445b483eb5f4368fd39f75f6f122b00ce81aa/test/createStore.spec.ts#L304))

These tests show that `nanostores` allows to mutate store subscribers list during their reaction to store update - which is bad and can lead to crazy reactive bugs that are hard to catch.
This is the very reason why Redux [creates shallow copy of subscribers array](https://github.com/reduxjs/redux/blob/184445b483eb5f4368fd39f75f6f122b00ce81aa/src/createStore.ts#L123) on **every dispatch** - and implementing the same fix seems possible with current `nanostores` design

This fix will not make `nanostores` glitch-less, but, at least, will solve some of the possible problems

**Comment by ai** [comment]
> diamond problem will come very soon anyway.

With big stores it will come later, because you do not need to have long chains of derived stores.

At least, I do not see these stores in my upcoming projects.

It is still a problem and I will think for solution.

**Comment by ai** [comment]
Seems like we need to backport subscribers cloning from Nano Events to fix the problems on changing listeners in the middle of reaction.

I will do it later.

**Comment by ai** [comment]
I started to swallow copy the listeners array https://github.com/nanostores/nanostores/commit/242d2b123ba4ccb7f11687fae40f70a3878b8bcc

And added note about diamond problem  https://github.com/nanostores/nanostores/commit/e5cfc5a8841c350b8a225fa908d25dd4095f4950

For now, I am closing the issue, since I do not know about the solution for Nano Stores design.

But if somebody will have an idea, please open an issue.

**Comment by ai** [comment]
Seems like we have a solution https://github.com/nanostores/nanostores/pull/58
