### ISSUE TITLE
`0.10.0` Minor release removed `action()` without upgrade guide

### ISSUE THREAD

**Issue by evadecker** [nanostores/nanostores#314]
Hi!

I'm using nanostores on one of my Astro projects, it's a helpful utility. Thanks for making it.

Today I attempted upgrading from `0.9.5` to `0.10.3` but tests failed because nanostores removed `action()`. The only reference I can find to this is a single line in the release notes without explanation of why it was removed or what to replace it with. Could some documentation be written?

**Comment by ai** [comment]
Thanks. I added reasons to `Releases`:

> It was useful only for logger which is not very popular. But `action()` API is complicated, and it makes state manager more complicated.

The simple function is better.

**Comment by evadecker** [comment]
Had the impression that `action` was required for nanostores, nice to know you can just use a function! Thank you for clarifying.
