### ISSUE TITLE
Actialize minimal size info in readbe and "about" section

### ISSUE THREAD

**Issue by Akiyamka** [nanostores/nanostores#316]
nanostores has grown in size, now the minimum size is 351 B (gzip)
That's about a 31% increase
https://bundlejs.com/?q=nanostores&treeshake=%5B%7B+atom+%7D%5D

**Comment by ai** [comment]
We use different metric from Size Limit tool. 

It creates new esbuild/webpack project, add file to it and check JS bundle size *difference*.

We think it is more accurate metric for the cost of the library in the real project.
