### ISSUE TITLE
deprecated modules and error handling exception in Astro.build framework

### ISSUE THREAD

**Issue by leoneldonati** [nanostores/nanostores#319]
This is a error message with Nanostores instalated:
✘ [ERROR] No loader is configured for ".html" files: node_modules/.pnpm/@mapbox+node-pre-gyp@1.0.11/node_modules/@mapbox/node-pre-gyp/lib/util/nw-pre-gyp/index.html

    node_modules/.pnpm/@mapbox+node-pre-gyp@1.0.11/node_modules/@mapbox/node-pre-gyp/lib/node-pre-gyp.js:86:21:
      86 │ ...urn require('./' + command)(self, arg...
         ╵                ~~~~~~~~~~~~~~

✘ [ERROR] Could not resolve "mock-aws-s3"

    node_modules/.pnpm/@mapbox+node-pre-gyp@1.0.11/node_modules/@mapbox/node-pre-gyp/lib/util/s3_setup.js:43:28:
      43 │ ...k = require('mock-aws-s3').catch((e) ...
         ╵                ~~~~~~~~~~~~~

  You can mark the path "mock-aws-s3" as external to
  exclude it from the bundle, which will remove this
  error and leave the unresolved path in the bundle.
  You can also surround this "require" call with a
  try/catch block to handle this failure at run-time
  instead of bundle-time.

✘ [ERROR] Could not resolve "aws-sdk"

    node_modules/.pnpm/@mapbox+node-pre-gyp@1.0.11/node_modules/@mapbox/node-pre-gyp/lib/util/s3_setup.js:76:22:
      76 │ ...AWS = require('aws-sdk').catch((e) =>...
         ╵                  ~~~~~~~~~

  You can mark the path "aws-sdk" as external to
  exclude it from the bundle, which will remove this
  error and leave the unresolved path in the bundle.
  You can also surround this "require" call with a
  try/catch block to handle this failure at run-time
  instead of bundle-time.

✘ [ERROR] Could not resolve "nock"

    node_modules/.pnpm/@mapbox+node-pre-gyp@1.0.11/node_modules/@mapbox/node-pre-gyp/lib/util/s3_setup.js:112:23:
      112 │ ...nock = require('nock').catch((e) => ...
          ╵                   ~~~~~~

  You can mark the path "nock" as external to exclude
  it from the bundle, which will remove this error and
  leave the unresolved path in the bundle. You can
  also surround this "require" call with a try/catch
  block to handle this failure at run-time instead of
  bundle-time.

----

JOIN IMAGE:
![Captura desde 2024-07-04 20-46-49](https://github.com/nanostores/nanostores/assets/113395484/9befde8a-0767-407d-833c-61f019f8b221)

**Comment by ai** [comment]
Sorry, this error messages don’t look like relevant to Nano Stores.

You need to ask Astro team. Very likely that these errors comes from Node.js and environment in general.
