### ISSUE TITLE
Multiple re-renders | React

### ISSUE THREAD

**Issue by sitarass** [nanostores/nanostores#325]
I have implemented a hook fetcher which takes the fetcher's data (@nanostores/query used) from useStore. However, I am observing with console log that the same data is logged multiple times causing a re-render in to the consumer components.

```
const useData = <T, E>(fetcher: FetcherStore<T, E>) => {
  const { data, error, loading: validating } = useStore(fetcher);
  console.log(data);

  const loading = validating && !data && !error;

  return {
    data,
    error,
    mutate: fetcher.revalidate,
    loading,
    validating,
    actions: {
      invalidate: fetcher.invalidate,
      revalidate: fetcher.revalidate,
      mutate: fetcher.mutate,
    },
  };
};
```

**Comment by ai** [comment]
It could be related with `@nanostore/fetch` (it is a project from another maintainer, I am not very familiar with code to help).

Can you reproduce it with `atom`?

**Comment by sitarass** [comment]
@ai To avoid re-renders with atoms I assign atoms returned from useStore to React states example bellow:
```
const configuration = useStore($api_configuration);
  const [request] = useState({
    customerId: configuration.customerId,
    ...initialRequest,
  });
```

**Comment by sitarass** [comment]
$api_configuration store
```
export const $api_configuration: MapStore<{
  baseUrl: string;
  headers?: Record<string, string>;
  channel?: string;
  customerId?: string;
}> = map({
  baseUrl: '',
  headers: undefined,
  channel: '',
  customerId: '',
});
```

**Comment by sitarass** [comment]
@ai 
I can't replicate it with an `atom`, sorry. The example above is using `map`.
I think the problem is with `@nanostores/query'.

**Comment by ai** [comment]
Yes, can you open an issue there?

**Comment by sitarass** [comment]
@ai done
