### ISSUE TITLE
Dead code in repo

### ISSUE THREAD

**Issue by NicoToff** [nanostores/nanostores#328]
I've stumbled upon a file in your project that seemingly used to be a test file but does nothing now.

https://github.com/nanostores/nanostores/blob/main/task%2Ftypes.ts

No big deal, but it's always nice to get rid of the clutter.

And congrats on `nanostores`, it's a really neat piece of software for the web 🎉

**Comment by ai** [comment]
Yes, it is test for types. We need to keep it in the project to be sure that we have no regressions.

We use [`check-dts`](https://github.com/ai/check-dts) to test types on every commit.

Don’t worry, we don’t have them in npm package https://github.com/nanostores/nanostores/blob/main/.npmignore#L2-L3

**Comment by NicoToff** [comment]
Aaah, it makes sense! Thanks for the quick reply.
