### ISSUE TITLE
What do after remove action from nanostores

### ISSUE THREAD

**Issue by gitlobster** [nanostores/nanostores#329]
My code uses the action function many times. How do I update nanostores, but not rewrite the entire code?

**Comment by gismya** [comment]
Use a normal function.

```
  function setNames(watermarks: string[]) {
    $watermarks.set(names);
  }

  setNames(["Alice","Bob"]);
```

**Comment by ai** [comment]
Another way is to copy `action()` from previous version to your project. It is just few lines of code helper.

**Comment by euaaaio** [comment]
@gitlobster, you can try to install next version of Logger for Nano Stores from `@nanostores/logger#feat/actions-api`. It has the same Actions API. This feature is not released as I haven't tested it in real life project yet, just e2e tests coverage.

**Comment by gitlobster** [comment]
> Use a normal function.
> 
> ```
>   function setNames(watermarks: string[]) {
>     $watermarks.set(names);
>   }
> 
>   setNames(["Alice","Bob"]);
> ```
I've used it many times and plus I've used the logger




> @gitlobster, you can try to install next version of Logger for Nano Stores from `@nanostores/logger#feat/actions-api`. It has the same Actions API. This feature is not released as I haven't tested it in real life project yet, just e2e tests coverage.

thanks

> Another way is to copy `action()` from previous version to your project. It is just few lines of code helper.
thanks
