### ISSUE TITLE
computed and batched expect full store type while having a subscribe method should be enough

### ISSUE THREAD

**Issue by wighawag** [nanostores/nanostores#340]
I like to design my store to only expose subscribe + write function

unfortunately `computed` and `batched` expect the full store type

Example

the time store:

```ts
//time.ts
import { atom, onMount } from "nanostores";

const $currentTime = atom<number>(Date.now());

onMount($currentTime, () => {
  $currentTime.set(Date.now());
  const updating = setInterval(() => {
    $currentTime.set(Date.now());
  }, 1000);
  return () => {
    clearInterval(updating);
  };
});

export const time = {
  subscribe: $currentTime.subscribe,
};
```

the timeSinceStart store:

```ts
import { computed } from "nanostores";
import { time } from "./time.js";

const appStarted = Date.now();

export const $userInApp = computed(time, (currentTime) => {
  return currentTime - appStarted;
});
```

this failed with 

```
No overload matches this call.
  The last overload gave the following error.
    Argument of type '{ subscribe: (listener: (value: number, oldValue?: number | undefined) => void) => () => void; }' is not assignable to parameter of type 'AnyStore[]'.
      Type '{ subscribe: (listener: (value: number, oldValue?: number | undefined) => void) => () => void; }' is missing the following properties from type 'AnyStore[]': length, pop, push, concat, and 35 more.ts(2769)
index.d.ts(53, 3): The last overload is declared here.
(alias) const time: {
    subscribe: (listener: (value: number, oldValue?: number | undefined) => void) => () => void;
}
```

**Comment by ai** [comment]
It is very specific use case. To support it we need to increase the complexity of our type system which will lead to other issues (like unclear types for new users).

I need really good rational reasons for this approach to support it.

I suggest you to create a wrapper around `computed` with custom types or hack type system by adding `global.d.ts`

**Comment by wighawag** [comment]
I uses this all the time to ensure user of the store cannot modified it in uninted ways and I think it is a popular in the svelte ecosystem to do that

By this I mean having read-only store. svelte even provide a utility to easily transform writable into readable

And once we have readable we assume we can still use `computed` or `batched`

So this is the rationale. 

As for unclear type, in svelte I don't see any problem, but maybe I am not seeing the whole picture

**Comment by gismya** [comment]
I coerce my store types as `ReadableAtom` when they leave the store code for similar reasons. If that's not enough, you should be able to fairly easily create a utility that removes access to the `set()` method and changes the type to `ReadableAtom`

**Comment by wighawag** [comment]
@gismya thanks!

I got that working :

```
import type { ReadableAtom, WritableAtom } from "nanostores";

export function readonly(atom: WritableAtom): ReadableAtom {
  const { set, ...readable } = atom;
  return readable;
}
```

**Comment by gismya** [comment]
That might work for your use case, but I'd recommend rewriting it to use [proxy objects](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) instead to allow the primitive values also to keep being linked between the objects.

**Comment by wighawag** [comment]
I see, i also like to add the writable function to the store object in svelte

But indeed looking at the nanostore code, the best is to use proxy or to modify the object dirextly. Removing "set" and adding fields
