### ISSUE TITLE
Add integration for React Native

### ISSUE THREAD

**Issue by LosYear** [nanostores/nanostores#38]
Hi! 

I'd like to use nanostores with React Native, but now it throws error on 'react-dom'. Are there any ways to do it? If no, I'd like to commit a PR. Are any tips how to implement it? Seems, like we could just remove `unstable_batchedUpdates` for RN integration

**Comment by ai** [comment]
`unstable_batchedUpdates` is a way to batch changes which affect on performance. We can’t just remove it.

How does Redux support RN in React hooks?

We can give another file for RN by replacing `react/index.js` via `package.json`. But what batching scheduler we can use for RN?

**Comment by LosYear** [comment]
Seems, like RN exports same function `unstable_batchedUpdates`

**Comment by ai** [comment]
Cool! Do you want to send PR to `next`?

**Comment by LosYear** [comment]
Yes, I do!

Should we create folder `react-native` and just copy-paste the previous code with replaced import? Can we do something better that this?

**Comment by ai** [comment]
> Should we create folder react-native

Nope. It will block reusing React components in RN. 

It is better to use this method https://github.com/ai/nanoid/blob/main/package.json#L27-L29

**Comment by ai** [comment]
I added React Native support in 1c8f036

Can you test it by install Nano Stores from `next` branch:

```
yarn add nanostores@nanostores/nanostores#next
```

Note, that router and persistent was moved to separated projects in `next`
