### ISSUE TITLE
Interest: How does this library differ from zustand?

### ISSUE THREAD

**Issue by felixhaeberle** [nanostores/nanostores#39]
Hey, I recently discovered this great library and want to ask how this library differs from the popular hook based library zustand, which also gives a pretty similar API to work with states. 

I want to decide whether to use nanostores or zustand and don't want to figure out the nuances bits when it's almost too late.

I would really appreciate an answer and thank the maintainer and creator of this module for their awesome work. 💐

**Comment by ai** [comment]
The main difference: Nano Stores was created to move logic from React component (or other UI library) into state manager.

This is why stores in Nano Stores have constructor (to bind event listeners), destructor and active/disabled mode.
