### ISSUE TITLE
Store with functional values and TypeScript

### ISSUE THREAD

**Issue by davidmz** [nanostores/nanostores#56]
I need to hold function in the store and use it with React. It works fine at JS level, but TS produces some type errors. Please look at this sandbox example: https://codesandbox.io/s/misty-dawn-t5t4v?file=/src/App.tsx:273-352

It seems that Readonly&lt;Fn> is not a callable function from a TS point of view.

**Comment by ai** [comment]
Hm. Seems like we need a hack like https://github.com/nanostores/nanostores/blob/09839cc4ecc3e61b920c56cd3af01b395c6e9160/create-store/index.d.ts#L1-L5

I will see today or tomorrow.

**Comment by ai** [comment]
Sorry. Had no time. You are welcome to send PR, I will be able to fix it only tomorrow or after tomorrow.

**Comment by ai** [comment]
Should be fixed in 3271416

**Comment by ai** [comment]
The fix was released 0.4.8
