### ISSUE TITLE
Advanced lifecycle

### ISSUE THREAD

**Issue by ai** [nanostores/nanostores#59]
In Nano Stores 0.5 we can copy lifecycle from `dotto.x`. The plan:

Events:
- `onStart` for first listener
- `onStop` for last listener
- `onChange`/`onSet` on data changes

API: `onStart(store, event => {})`. `event` will contain `store`, `abort` (for `onChange` and `onSet`), `stopPropagation`, `data`.

Questions:
1. What is the difference between `onChange` and `onSet` in `dotto.x`?
2. Do we really need `onGet`?

Plan:
1. Add lifecycle code
2. Remove store auto-cleaning and use  lifecycle
3. Add `mount` helper to set `onStart` and `onStop` with delay after `onStop`
4. Use `mount` in `deprecated/index.js` store creators

/cc @Eddort

**Comment by Eddort** [comment]
> What is the difference between onChange and onSet in dotto.x?

`onChange` is calling before listeners emitted. It is useful for a transaction or some logic with deep watching. We can skip listener calls. (`abort` function).

`onSet` is calling before changes applied and we can prevent it. This behavior is useful for validation and skipping invalid data.

> Do we really need onGet?

I think we don't

What do you think about `getValue` function? In my realization `get` is part of the `atom`. Can I  implement `createAtom` same as in **dotto.x**? [createAtom in dotto.x](https://github.com/dottostack/dotto.x/blob/main/packages/dotto.x/create-atom/index.js)

**Comment by ai** [comment]
> What do you think about getValue function? In my realization get is part of the atom. Can I implement createAtom same as in dotto.x? createAtom in dotto.x

Looks good. But we need to override `store.get` to call `onStart` on 0 listeners to initialize store before reading.

**Comment by Eddort** [comment]
Alright, I will prototype it tomorrow. But it requires that PR https://github.com/nanostores/nanostores/pull/60

**Comment by ai** [comment]
> Alright, I will prototype it tomorrow. But it requires that PR

I will try to merge it faster, but afraid it will be only after tomorrow.

No rush :)

**Comment by ai** [comment]
@Eddort #60 was merged

**Comment by Eddort** [comment]
FIne! I’ve already started

**Comment by ai** [comment]
Closed in https://github.com/nanostores/nanostores/pull/62
