### ISSUE TITLE
Nanostores Missunderstanding In react native

### ISSUE THREAD

**Issue by electroheadfx** [nanostores/nanostores#61]
Iam implementing a simple exemple with useStore counter in main composant and another component is modifying it with a increaseCounter() but I got an error :

"Warning: Cannot update a component from inside the function body of a different component."

If I manage increaseCounter from the same main component it works, so how implement a store change from others components ? is not the purpose ?
Iam sure I have missed something.

thanks

**Comment by ai** [comment]
Where do you run `increaseCounter`?

**Comment by electroheadfx** [comment]
my app structure are:
<OfflineNotice />
<LoginNavigator />
    <Login />


I run increaseCounter from <OfflineNotice /> and I read useState data from <Login />

**Comment by ai** [comment]
Show the code with `increaseCounter` run

**Comment by electroheadfx** [comment]
its just store counter:
```
import { createStore, getValue } from 'nanostores';

const counter = createStore(() => {
  counter.set(0);
});

function increaseCounter() {
  counter.set(getValue(counter) + 1);
}

function decreaseCounter() {
  counter.set(getValue(counter) - 1);
}

export { counter, increaseCounter, decreaseCounter };
```

I call it from OfflineNotice:
```
import { counter, increaseCounter } from '../store/Counter';
increaseCounter();
```

and read it in Login:
```
import { counter } from '../../store/Counter';
const count = useStore(counter);
return <Text>{count}</Text>
```

**Comment by electroheadfx** [comment]
aah but I can't do that, the data is updated from the component logic itself:

```
import { counter, increaseCounter, decreaseCounter } from '../store/Counter';
function OfflineNotice(props) {
  const netInfo = useNetInfo();
  if (netInfo.type !== 'unknown' && netInfo.isInternetReachable === false) {
    switchOffline(true);
    decreaseCounter();
    console.log('offline');
    return (
      <View style={styles.container}>
        <Text style={styles.text}>No Internet Connection</Text>
      </View>
    );
  }
  console.log('online');
  increaseCounter();
  switchOffline(false);
  return null;
}
```

**Comment by ai** [comment]
You can’t change data in the component’s render.

Sorry, I am closing this issue, since it is a question about React Native.

**Comment by electroheadfx** [comment]
Sorry to re-open, I got this error but the data is well updated in the Login Screen (counter is 3) instead of default (0), and I can update again from Login Screen.

**Comment by ai** [comment]
Try to use `useEffect()` to call changes during render

**Comment by electroheadfx** [comment]
Work with a useEffect, thanks
