### ISSUE TITLE
Use subscribe API in React 18

### ISSUE THREAD

**Issue by ai** [nanostores/nanostores#68]
https://github.com/reactwg/react-18/discussions/86

https://twitter.com/acemarke/status/1444736773142241285

**Comment by nikolay-govorov** [comment]
Hi. Sounds like a really cool idea! I am selecting store for my work and it is a beautiful wrapper for asynchronous data loading - the only thing I would like in nanostores.

If it was +- compatible with how Recoil does it, it would be great. More about _Facebook way_: https://recoiljs.org/docs/guides/asynchronous-data-queries

**Comment by IgnusG** [comment]
The react wrapper of https://github.com/pmndrs/valtio (another state management library - somewhat similar to nanostores) also uses React Suspense to transparently allow async values in stores - as in suspends until the promise resolves.

**Comment by ai** [comment]
Was used already https://github.com/nanostores/react/blob/main/index.js#L3
