### ISSUE TITLE
Object as value in map?

### ISSUE THREAD

**Issue by zgoda** [nanostores/nanostores#84]
My API returns complete related object along with item data and I wanted to store it in a map store but when reading store I'm always getting `undefined` for that key - is this some kind of limitation?

**Comment by ai** [comment]
Can you show an example?

**Comment by zgoda** [comment]
Example data from API:

```
{
    "event": {
        "created": 1637172541892,
        "date": 1639785600000,
        "description": null,
        "id": 2,
        "length": 20,
        "location": "Polska",
        "name": "W Polskę idziemy",
        "public": true,
        "user": {
            "displayName": "Pan Jan",
            "email": "jasiu@example.com",
            "isActive": true,
            "name": "Pan Jan"
        },
        "virtual": true
    }
}
```

Object def:

```
export interface EventData {
  id: string;
  user?: User;
  created?: Date;
  name: string;
  date: Date;
  length: number;
  location: string;
  virtual: boolean;
  public: boolean;
  description?: string;
}
```

The object that is passed to `store.set()` definitely contains `user` key but when read with `useStore(EventStore(eventId))` the `user` key is missing.

**Comment by ai** [comment]
It should work.

Show the example of code where you put value to the store and read it.

**Comment by zgoda** [comment]
Store:

```
export const EventStore = mapTemplate(
  (
    /** @type {import('nanostores').MapStore<import('../..').EventData>} */ store,
    id,
  ) => {
    fetchEvent(id).then((evt) => store.set({ ...evt, id }));
  },
);
```

It's later read in a component with `const event = useStore(EventStore(params.id.toString()));`.

This is in Preact if that makes any difference.

**Comment by ai** [comment]
Show the `event` values during the application work

**Comment by zgoda** [comment]
![Zrzut ekranu z 2021-11-21 18-44-13](https://user-images.githubusercontent.com/141999/142773106-2ff627ae-64a4-41db-8c0d-8e3ff8ad828c.png)

**Comment by ai** [comment]
This is a only first render.

Your `fetchEvent` is async operation. It needs a time to download `evt`. So on some first seconds store will have only `{ id }` because `fetchEvent(id).then(cb)` was not finished.

**Comment by zgoda** [comment]
You're right, PEBKAC.

Thank you.
