### ISSUE TITLE
Subscribe to multiple atoms

### ISSUE THREAD

**Issue by mrjjwright** [nanostores/nanostores#91]
Why can `computeds` depend on multiple atoms but a `subscribe` is only to a single atom?   Just curious.   

Also, do you all believe strongly in explicit dependencies, I assume so, and if so why?   I am just curious as I like them being explicit as it's easier for me to reason about  but many argue that dependencies should be tracked automatically like Mobx, Solid, Vue, etc.

**Comment by ai** [comment]
> Why can computeds depend on multiple atoms but a subscribe is only to a single atom?

No special reason.

`subscribe` is an object’s method, and I just do not know how to pass multiple items there.

> Also, do you all believe strongly in explicit dependencies, I assume so, and if so why?

Can you show an example of non-explicit dependencies to fully understand the question.

**Comment by mrjjwright** [comment]
E.g. Solid and Vue automatically track dependencies as the `subscribe` or `computed` runs instead of having to specify them explicitly.   It's ok, no big deal, thanks for the help!
