### ISSUE TITLE
You can't use `onMount` on `computed`

### ISSUE THREAD

**Issue by AleksandrSl** [nanostores/nanostores#94]
Found by @dkzlv

Repro: https://codesandbox.io/s/compassionate-bohr-e4bpx?file=/src/App.js

Expected:
The callback returned from `onMount` shouldn't be called. Because we always stay subscribed

Harsh reality:
The callback returned from `onMount` is called.

Explanation:
When we return store from computed we do destructuring of the internal derived store. Thus returning the initial `lc: 0` and we never update it. All subscriptions change `lc` of the internal derived.

Thus `onMount` think that we have no listeners and calls "unmount code"

Possible Fix:
The simplest fix is to return the same store:
```
derived.deps = deps
return derived
```
instead of 
```
return {
  deps,
  ...derived
}
```

If we can't do this for some security reasons or anything. We should highjack the `derived` `listen` method

**Comment by ai** [comment]
Can you send PR with possible fix?

Looks it will fix the problem.

cc @Eddort

**Comment by ai** [comment]
Fixed https://github.com/nanostores/nanostores/commit/b76e07a4d2ddfd8f8245373746a7bf24ab6d8fe9

**Comment by AleksandrSl** [comment]
Thanks!
