### ISSUE TITLE
Support for Lit

### ISSUE THREAD

**Issue by JosefJezek** [nanostores/nanostores#95]
Could you add support for Lit? https://lit.dev

Astro natively supports the Lit. https://astro.build

**Comment by ai** [comment]
Sure, Lit is cool.

Do you want to start and support `nanostores/lit`? If it becomes popular, we will add it to the core library.

If you agree to become a maintainer, create a repo and ping me when it will be ready. I will review it, give you an access, and you will be able to move it to `nanostores` org.

**Comment by akowi-sknobloch** [comment]
You already can use `nanostores` pretty easy with Lit.
Just bind your store in your Components constructor and map it to states or properties kinda like so:

```ts
import { users } from './stores/users';

@customElement('user-list')
class UserList extends LitElement {
  @state()
  _users = [];

  constructor() {
    super();

    users.subscribe(this.mapUsersState.bind(this));
  }

  mapUsersState(userList) {
    this._users = userList;
  }

  render() {
    return html`
      <ul>${this._users?.map((user) => html`<li>${user.name}</li>`)}</ul>
    `;
  }
}
```

This automatically re-renders the component, when the `users`-Store gets changed.
What additional benefits would you expect of an special "support" for Lit?

**Comment by blikblum** [comment]
This will leak element memory. Should unsubscribe in disconnectCallback.

**Comment by valtissimo** [comment]
@akowi-sknobloch The unsubscribe handler will be returned when you call `[subscribe()](see https://github.com/nanostores/nanostores/blob/main/atom/index.js#L54)` or `listen()`.  Save this handler and call it on disconnect. For me the return type definition of those function does not reflect this so I needed to cast it as Function:

```
private _unsubscribe?: Function

override connectedCallback() {
    super.connectedCallback()
    this._unsubscribe = myStore.subscribe((item: MyItemType) => {
      this._item = item
    }) as Function
  }

  override disconnectedCallback() {
    super.disconnectedCallback()
    this._unsubscribe!()
  }
```

**Comment by emilbonnek** [comment]
I made a generic [Reactive Controller](https://lit.dev/docs/composition/controllers/) for this and I think it works pretty nicely. (Although I don't know too much about neither Lit or `nanostores`).

**./nanostores/lit/useStore.ts**
```
import { ReactiveController, ReactiveControllerHost } from "lit";
import { WritableAtom } from "nanostores";

export class useStore<AtomType> implements ReactiveController {
  private _atom: WritableAtom<AtomType>;
  private _unsubscribe: () => void;
  public value: AtomType;

  constructor(host: ReactiveControllerHost, atom: WritableAtom<AtomType>) {
    this._atom = atom;
    this.value = this._atom.get();
    host.addController(this);
    this._unsubscribe = this._atom.subscribe((value) => {
      this.value = value;
      host.requestUpdate();
    });
  }

  // Unsubscribe from the store when the host disconnects
  hostDisconnected() {
    this._unsubscribe!();
  }
}
```

It can be used in Lit components like so:
```
import { LitElement, html } from "lit";
import { customElement } from "lit/decorators.js";
import { useStore } from "./nanostores/lit/useStore";
import { isCartOpen } from "./stores/cartStore";

@customElement("simple-demo")
export class SimpleDemo extends LitElement {
  private $isCartOpen = new useStore(this, isCartOpen);

  render() {
    return html`
      <h2>Simple Demo</h2>
      <input
        type="checkbox"
        .checked=${this.$isCartOpen.value}
        @change=${() => {
          isCartOpen.set(!this.$isCartOpen.value);
        }}
      />
    `;
  }
}
```
This overall seems very similar to the experience of using `nanostores` in Preact, React, Solid and Vue.

@ai Is this the kind of thing that could be turned into `nanostores/lit`? I never really did any open source so I don't know how all the stuff around publishing to npm works. I could probably look into it and spend some time on it though.

Repository with code and demos: [https://github.com/emilbonnek/lit-nanostores](https://github.com/emilbonnek/lit-nanostores)

**Comment by ai** [comment]
Looks nice. You can create your own repo, copying [our Preact integration](https://github.com/nanostores/preact/).

When I will check your code, we can move the project to `nanostores` org.

**Comment by emilbonnek** [comment]
I got some feedback in the Lit discord on this. This has sparked a few changes and some suggestions on how it can be improved. The thread is [here](https://discord.com/channels/1012791295170859069/1012791295942590597/threads/1059827149395218502). 

First it was suggested to remove the private `_value` field and just have a getter to obtain the value of the atom.
`get value() { return this._atom.get(); }` Then the subscription is really only the there to call `host.requestUpdate();` to let the component know to rerender.

Secondly the naming of `useStore` is not very intuitive when it is implemented as a Reactive Controller. Rather it could be named `StoreController`. And it was suggested to make a class decorator called `@useStore`/`@useStores` which would be applied to a Lit element and set up a `StoreController` so users could just access the atom's `.get()` method reactively. Like so:

```
@useStores([foo, bar])
class MyComponent extends LitElement {
   render() {
      return html`foo: ${foo.get()}, bar: ${bar.get()}`;
   }
}
```
I have updated the code in [the repository](https://github.com/emilbonnek/lit-nanostores) with these changes, and I will continue to play around with it a bit before I try to get something that's publishable.

**Comment by emilbonnek** [comment]
@ai Can you take a look at this?

https://github.com/emilbonnek/nanostores-lit

**Comment by ai** [comment]
@emilbonnek looks good. I sentyou invite to `nanostore` org. Feel free to move repo and send PR to Nano Stores docs.

**Comment by blikblum** [comment]
I have a different take using nanostores with lit.

I use a mixin to hook nanostores into lit reactive property system

I put in a package: https://github.com/blikblum/lit-nanostores

Among the benefits is that the component implementation is not tied to nanostores making easier to test: https://github.com/blikblum/lit-nanostores/blob/main/demo/message-banner.test.js#L8

**Comment by ai** [comment]
@blikblum can you create a `README.md` to understand the API?

**Comment by emilbonnek** [comment]
@blikblum I like the idea of using a mixin 👍
I have included one in my version too now alongside the other ways.
Mine still use a Reactive Controller though and it takes a list of atoms/stores as a secondary param and then calls requestUpdate on the LitElement when any of them updates. Like so:
```
export class MessageBanner extends withStores(LitElement, [message]) {
  render() { return html`<h1>${message.get()}</h1>`}
}
```

Is there any way you could make your version work with Typescript? I am struggling getting to work.

**Comment by emilbonnek** [comment]
@ai I added a draft PR #140 for updating the docs and I moved the repo into the nanostores organization.

**Comment by blikblum** [comment]
> @blikblum can you create a `README.md` to understand the API?

Done: https://github.com/blikblum/lit-nanostores

**Comment by blikblum** [comment]
Hopefully someday i will have time to write an article of the options to use app state (nanostores) in a Lit (web component) app.

Sneak peak: use [context](https://github.com/blikblum/wc-context/blob/master/examples/lazy-data/dataProvider.js#L6) or integrates [with a router](https://github.com/blikblum/wc-f7/blob/master/examples/router/pages/CatFactRoute.js#L12)

These two solutions work with any web component and is yet more decoupled than the direct integration with nanostores

**Comment by YoungElPaso** [comment]
> Hopefully someday i will have time to write an article of the options to use app state (nanostores) in a Lit (web component) app.
> 
> Sneak peek: use [context](https://github.com/blikblum/wc-context/blob/master/examples/lazy-data/dataProvider.js#L6) or integrates [with a router](https://github.com/blikblum/wc-f7/blob/master/examples/router/pages/CatFactRoute.js#L12)
> 
> These two solutions work with any web component and is yet more decoupled than the direct integration with nanostores

This looks great! I was just looking for a lit integration after coming to nanostores from the Astro docs. 

Any testing or anything that could use any help?

**Comment by ai** [comment]
Done https://github.com/nanostores/lit
