### ISSUE TITLE
Reset store value on cleanup

### ISSUE THREAD

**Issue by AndreiEres** [nanostores/nanostores#99]
What do you think if cleanup restores store initial value?
https://github.com/nanostores/nanostores/blob/f521da45b3dda93e8b8ca037c119fd6d5c67b9f4/atom/index.js#L52-L56
```
store.value = initialValue
```

**Comment by ai** [comment]
The practice showed that this behavior was unexpected for users.

But you can create custom `cleaningAtom`, which will clean value on `off`.
